// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID int32
}

type User struct {
	ID       pgtype.UUID
	Username string
	Birthday pgtype.Text
}
