CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
    username VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS posts(
    id SERIAL PRIMARY KEY NOT NULL
);
